package relics;

public enum RelicTypes {
	ASHEN_KING(Relic.ASHEN_KING),
	HERMES_SANDALS(Relic.HERMES_SANDALS),
	PHANTOM_BLADE(Relic.PHANTOM_BLADE),
	HOLLOW_BONES(Relic.HOLLOW_BONES),
	OBLIVION_RELIC(Relic.RELIC_OF_OBLIVION),
	SHARPENED_FANG_RELIC(Relic.RELIC_OF_SHARPENED_FANG),
	PATH_FINDER_RELIC(Relic.RELIC_OF_THE_PATHFINDER),
	WANDERING_STAR_RELIC(Relic.RELIC_OF_THE_WANDERING_STAR),
	MINERS_FORTUNE_RELIC(Relic.RELIC_OF_THE_MINERS_FORTUNE),
	ALCHEMIST_RELIC(Relic.RELIC_OF_THE_ALCHEMIST),
	FORSAKEN_RELIC(Relic.RELIC_OF_THE_FORSAKEN),
	TITANS_WILL_RELIC(Relic.RELIC_OF_THE_TITANS_WILL),
	ENDSEER_RELIC(Relic.RELIC_OF_THE_ENDSEER),
	INFERNAL_BEAST_RELIC(Relic.RELIC_OF_INFERNAL_BEAST),
	SONIC_BOW_RELIC(Relic.SONIC_BOW);
	
	private Relic relic;
	
	RelicTypes(Relic relic) {
		this.relic = relic;
	}
	
	public Relic getRelic() {
		return this.relic;
	}
}
